apiVersion: v1
kind: Service
metadata:
  name: theta
  labels:
    app.kubernetes.io/name: theta
    app.kubernetes.io/component: backend
spec:
  type: LoadBalancer
  ports:
  #- protocol: TCP
  #- port: 27318 # Public Port
  - port: 16988
    targetPort: 16888
    protocol: TCP
  selector:
    app.kubernetes.io/name: theta
    app.kubernetes.io/component: backend
